In [53]:
import numpy as np
import tensorflow as tf

In [54]:
a=[[1,2,3],[4,5,6]]
a=tf.constant(a,shape=(3,2),dtype='float32')

In [55]:
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [56]:
a.dtype

tf.float32

In [57]:
b=[[1,2,3],[4,5,6]]
b=tf.constant(b,shape=(3,2),dtype='float32')

In [58]:
b

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [59]:
## element wise multiplication
print(a*b)
# element wise addition
print(a+b)

## matrix multiplication
## the two matrices should not be of same shape
b=tf.reshape(b,shape=(2,3))
print(a @ b)

tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]
 [25. 36.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 9. 12. 15.]
 [19. 26. 33.]
 [29. 40. 51.]], shape=(3, 3), dtype=float32)


In [60]:
## maximum value in the matrix
tf.reduce_max(a)



<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [61]:
tf.reduce_max(a,axis=1,keepdims=True)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[2.],
       [4.],
       [6.]], dtype=float32)>

In [62]:
tf.reduce_max(a,axis=0,keepdims=True)
## axis=0 is the axis which is across rows.

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5., 6.]], dtype=float32)>

In [63]:
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [64]:
a=tf.Variable(a)

In [65]:
a

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [66]:
a[1].assign([100,200])

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[  1.,   2.],
       [100., 200.],
       [  5.,   6.]], dtype=float32)>

In [67]:
a[0].assign([200,300])

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[200., 300.],
       [100., 200.],
       [  5.,   6.]], dtype=float32)>

In [68]:
a.is_initialized()
## to immediately check whether the variable is initialized or not?

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [69]:
tf.random.normal(shape=(2,3),mean=10,stddev=10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[23.165417 , 16.19848  ,  4.415596 ],
       [ 8.166712 ,  6.1606016, 24.877026 ]], dtype=float32)>

In [70]:
tf.random.shuffle(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  5.,   6.],
       [200., 300.],
       [100., 200.]], dtype=float32)>

In [71]:
a[...,tf.newaxis]

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[200.],
        [300.]],

       [[100.],
        [200.]],

       [[  5.],
        [  6.]]], dtype=float32)>

In [72]:
a[tf.newaxis,...]

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[200., 300.],
        [100., 200.],
        [  5.,   6.]]], dtype=float32)>

In [73]:
a

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[200., 300.],
       [100., 200.],
       [  5.,   6.]], dtype=float32)>

In [74]:
tf.expand_dims(a,axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[200., 300.]],

       [[100., 200.]],

       [[  5.,   6.]]], dtype=float32)>

In [75]:
a[tf.newaxis,...]

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[200., 300.],
        [100., 200.],
        [  5.,   6.]]], dtype=float32)>

In [76]:
## the result of the matrix multiplication is the outer dimensions.
## the inputs rows of one matrix should be the same as columns as other matrix.

In [77]:
a=tf.random.normal(shape=(2,3),mean=0,stddev=1)
b=tf.random.normal(shape=(3,2),mean=0,stddev=1)

In [78]:
a,b

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.7879332 ,  0.7871286 , -1.087564  ],
        [-1.3422972 , -0.70235676, -0.02671925]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.26273942, -0.40642062],
        [-1.0357411 ,  0.415366  ],
        [ 0.05440439,  0.9193911 ]], dtype=float32)>)

In [79]:
a@b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.66740865, -0.9931825 ],
       [ 0.37333173,  0.22923668]], dtype=float32)>

In [80]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.66740865, -0.9931825 ],
       [ 0.37333173,  0.22923668]], dtype=float32)>

In [81]:
tf.tensordot(a,b,axes=0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=float32, numpy=
array([[[[ 0.2070211 , -0.32023227],
         [-0.81609476,  0.32728064],
         [ 0.04286703,  0.72441876]],

        [[ 0.20680971, -0.3199053 ],
         [-0.8152615 ,  0.32694647],
         [ 0.04282326,  0.72367907]],

        [[-0.28574592,  0.44200844],
         [ 1.1264347 , -0.4517371 ],
         [-0.05916826, -0.99989665]]],


       [[[-0.3526744 ,  0.54553723],
         [ 1.3902724 , -0.5575446 ],
         [-0.07302687, -1.234096  ]],

        [[-0.1845368 ,  0.28545228],
         [ 0.7274597 , -0.2917351 ],
         [-0.03821129, -0.64574057]],

        [[-0.0070202 ,  0.01085925],
         [ 0.02767422, -0.01109827],
         [-0.00145364, -0.02456544]]]], dtype=float32)>

In [82]:
## to change the datatype of a tensor
tf.cast(a,tf.float64)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 0.78793317,  0.78712863, -1.08756399],
       [-1.3422972 , -0.70235676, -0.02671925]])>

In [83]:
#if you want to sqeeze the single dimensions from the tensor, you can use squeeze function
a=tf.expand_dims(a,axis=0)


In [84]:
a=a[tf.newaxis,tf.newaxis,...]

In [85]:
tf.squeeze(a)
## one squeeze removes all the one dimensions.

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.7879332 ,  0.7871286 , -1.087564  ],
       [-1.3422972 , -0.70235676, -0.02671925]], dtype=float32)>

In [86]:
## one hot encoding
somelist=[0,1,2,3,4]
tf.one_hot(somelist,depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [87]:
def function(x,y):
  return x**2+y

In [88]:
%time
x=tf.constant(np.arange(100000000))
y=tf.constant(np.arange(100000000))
function(x,y)

CPU times: user 4 µs, sys: 2 µs, total: 6 µs
Wall time: 11.2 µs


<tf.Tensor: shape=(100000000,), dtype=int64, numpy=
array([               0,                2,                6, ...,
       9999999500000006, 9999999700000002, 9999999900000000])>

In [89]:
%time
@tf.function
def tf_function(x,y):
  return x**2+y
tf_function(x,y)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 9.06 µs


<tf.Tensor: shape=(100000000,), dtype=int64, numpy=
array([               0,                2,                6, ...,
       9999999500000006, 9999999700000002, 9999999900000000])>

In [90]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [91]:
!nvidia-smi

Mon Mar 28 07:51:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    65W / 149W |   8387MiB / 11441MiB |     24%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#Exercises

In [183]:
#1
a=tf.constant(7)
print(a)
print(a.shape)
print(a.ndim)

tf.Tensor(7, shape=(), dtype=int32)
()
0


In [184]:

a=tf.constant([7,8])
print(a)
print(a.shape)
print(a.ndim)

tf.Tensor([7 8], shape=(2,), dtype=int32)
(2,)
1


In [185]:
a=tf.constant([[7,8],[4,5]])
print(a.shape)
print(a)
print(a.ndim)

(2, 2)
tf.Tensor(
[[7 8]
 [4 5]], shape=(2, 2), dtype=int32)
2


In [186]:
a=np.random.randn(64,64,3)
a=tf.constant(a)
print(a.shape)
print(a)
print(a.ndim)

(64, 64, 3)
tf.Tensor(
[[[-3.87303508e-01 -4.69295811e-01  5.37297596e-01]
  [ 2.11751629e-01  1.58003957e+00 -7.30491766e-01]
  [-5.40622507e-01  2.12032798e-01  9.13515523e-01]
  ...
  [ 1.46072081e-01  1.03891942e-02 -1.38249037e+00]
  [-1.33118143e+00  9.52693334e-02  6.59449108e-01]
  [ 1.00657911e+00 -1.13444207e+00  1.75088625e+00]]

 [[-8.33305134e-01 -5.25589360e-02  1.65977470e+00]
  [ 6.69034646e-01  1.70841461e-01  3.29798067e-01]
  [-1.43429869e-01 -4.26382669e-02  1.27899253e+00]
  ...
  [ 1.29673215e+00  2.21139501e+00 -1.98075044e+00]
  [-2.03909002e+00 -1.08284078e+00  1.14935511e+00]
  [ 4.49744898e-01  1.13722207e+00  1.07160047e+00]]

 [[ 1.38293242e-01  4.64682976e-02  8.03613999e-02]
  [ 9.59078797e-02  4.00609214e-01 -2.00917929e+00]
  [-6.13521301e-01  1.44699071e+00 -1.95740109e-01]
  ...
  [ 9.56956431e-02 -7.35792131e-01 -2.41075470e-01]
  [-9.41654897e-01 -1.64979360e+00 -1.11197367e+00]
  [-4.09456665e-04  5.37649113e-01 -6.82259807e-01]]

 ...

 [[-7.11658

In [187]:
#3
a=tf.random.uniform(shape=(5,300),minval=0,maxval=1)
b=tf.random.uniform(shape=(5,300),minval=0,maxval=1)

In [188]:
#4
tf.matmul(a,tf.transpose(b))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.81986 , 76.03356 , 71.97693 , 74.72475 , 78.44449 ],
       [75.71071 , 72.93967 , 73.30892 , 74.824196, 77.78872 ],
       [73.6935  , 74.08628 , 71.080315, 75.03168 , 73.63146 ],
       [80.06328 , 77.70247 , 74.60313 , 81.810356, 80.274086],
       [78.25927 , 73.57877 , 75.06772 , 78.31542 , 77.77592 ]],
      dtype=float32)>

In [189]:
#4
tf.tensordot(a,tf.transpose(b),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.81986 , 76.03356 , 71.97693 , 74.72475 , 78.44449 ],
       [75.71071 , 72.93967 , 73.30892 , 74.824196, 77.78872 ],
       [73.6935  , 74.08628 , 71.080315, 75.03168 , 73.63146 ],
       [80.06328 , 77.70247 , 74.60313 , 81.810356, 80.274086],
       [78.25927 , 73.57877 , 75.06772 , 78.31542 , 77.77592 ]],
      dtype=float32)>

In [190]:
#5
tf.tensordot(a,b,axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[7.10551918e-01, 2.95317974e-02, 3.12610209e-01, ...,
          2.22665370e-01, 2.98033625e-01, 1.62707850e-01],
         [5.29065728e-01, 1.44152030e-01, 5.83182797e-02, ...,
          7.17305765e-02, 5.40486090e-02, 5.30811191e-01],
         [7.05810487e-01, 1.69586226e-01, 8.02313089e-01, ...,
          2.35534489e-01, 6.48823529e-02, 6.16474390e-01],
         [3.00731450e-01, 6.24275208e-01, 4.45724905e-01, ...,
          7.55782008e-01, 7.23155797e-01, 3.30035299e-01],
         [6.83836520e-01, 6.70659900e-01, 8.26017082e-01, ...,
          5.89658737e-01, 6.23449206e-01, 7.67040431e-01]],

        [[5.02472401e-01, 2.08836440e-02, 2.21064776e-01, ...,
          1.57459587e-01, 2.10756838e-01, 1.15060151e-01],
         [3.74133021e-01, 1.01938248e-01, 4.12402339e-02, ...,
          5.07248454e-02, 3.82209010e-02, 3.75367343e-01],
         [4.99119490e-01, 1.19924247e-01, 5.67362070e-01, ...,
          1.66560084e-0

In [191]:
#6
a=tf.random.uniform(shape=(1,224,224,3),minval=0,maxval=1)

In [192]:
print(tf.reduce_max(a).numpy())
print(tf.reduce_min(a).numpy())

0.9999845
2.6226044e-06


In [193]:
#7
a=tf.random.uniform(shape=(1,224,224,3),minval=0,maxval=1)
tf.squeeze(a)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[9.55696821e-01, 7.24289775e-01, 4.98284936e-01],
        [5.06071925e-01, 9.27577496e-01, 4.60139155e-01],
        [7.49034286e-01, 3.06905270e-01, 2.50339746e-01],
        ...,
        [3.75957131e-01, 2.03198433e-01, 2.22903967e-01],
        [9.45205569e-01, 1.13681555e-02, 7.23131776e-01],
        [9.64228392e-01, 5.02299070e-02, 2.44393706e-01]],

       [[5.13869524e-01, 9.96599197e-01, 8.24389577e-01],
        [2.33581424e-01, 7.09347129e-01, 2.67512798e-02],
        [1.92519069e-01, 4.48214293e-01, 7.41687536e-01],
        ...,
        [9.22751427e-03, 9.26254392e-01, 2.83317566e-02],
        [6.37668014e-01, 5.77263951e-01, 1.29481554e-01],
        [3.47725868e-01, 1.87308431e-01, 4.64456558e-01]],

       [[2.24637985e-02, 7.24700928e-01, 3.24611545e-01],
        [7.77771711e-01, 4.26566601e-01, 8.11135650e-01],
        [8.96891594e-01, 8.27131271e-02, 8.93657088e-01],
        ...,
        [5.59369206e-01, 3.46465

In [194]:
#9
a=np.array([22,4,1,55,6,7,8,34,90,12])
a=tf.Variable(a)
a=tf.reshape(a,shape=(10))
print(a)

tf.Tensor([22  4  1 55  6  7  8 34 90 12], shape=(10,), dtype=int64)


In [195]:
## max value
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int64, numpy=90>

In [196]:
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [197]:
## optional
## argmax() across different axes
a=tf.reshape(a,shape=(5,2))
a

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[22,  4],
       [ 1, 55],
       [ 6,  7],
       [ 8, 34],
       [90, 12]])>

In [198]:
tf.argmax(a,axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 1, 1, 0])>

In [199]:
tf.argmax(a,axis=0)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 1])>

In [200]:
#10
a=np.array([22,4,1,55,6,7,8,34,90,12])
a=tf.Variable(a)
a=tf.reshape(a,shape=(10))
print(a)

tf.Tensor([22  4  1 55  6  7  8 34 90 12], shape=(10,), dtype=int64)


In [201]:
one_hot_matrix=tf.one_hot(a,depth=10)
one_hot_matrix

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [202]:
## Optional
## grocery bill

In [203]:
items=['food','grocery','rent','drinks']

In [241]:
expenses=np.ones((12,4))

In [242]:
expenses[:,2]=600

In [228]:
expenses[:,0]=20

In [243]:
food_random=np.random.randint(20,100,12)

In [244]:
food_random

array([28, 38, 37, 79, 21, 41, 80, 51, 79, 26, 61, 52])

In [246]:
expenses[:,0]=food_random

In [247]:
expenses

array([[ 28.,   1., 600.,   1.],
       [ 38.,   1., 600.,   1.],
       [ 37.,   1., 600.,   1.],
       [ 79.,   1., 600.,   1.],
       [ 21.,   1., 600.,   1.],
       [ 41.,   1., 600.,   1.],
       [ 80.,   1., 600.,   1.],
       [ 51.,   1., 600.,   1.],
       [ 79.,   1., 600.,   1.],
       [ 26.,   1., 600.,   1.],
       [ 61.,   1., 600.,   1.],
       [ 52.,   1., 600.,   1.]])

In [248]:
groceries=random=np.random.randint(80,120,12)
groceries

array([ 92, 114, 114, 104,  84,  81,  95, 106,  88,  83,  92,  94])

In [251]:
expenses[:,1]=groceries

In [252]:
drinks=random=np.random.randint(1,20,12)
drinks

array([ 9,  4,  6, 19, 16, 15, 10,  5,  4, 16, 15,  1])

In [253]:
expenses[:,-1]=drinks

In [254]:
## now the expenses table is ready
## every row indicates the month

expenses

array([[ 28.,  92., 600.,   9.],
       [ 38., 114., 600.,   4.],
       [ 37., 114., 600.,   6.],
       [ 79., 104., 600.,  19.],
       [ 21.,  84., 600.,  16.],
       [ 41.,  81., 600.,  15.],
       [ 80.,  95., 600.,  10.],
       [ 51., 106., 600.,   5.],
       [ 79.,  88., 600.,   4.],
       [ 26.,  83., 600.,  16.],
       [ 61.,  92., 600.,  15.],
       [ 52.,  94., 600.,   1.]])

In [258]:
monthly_expenses=tf.reduce_sum(expenses,axis=1)
monthly_expenses
## monthly total for everything

<tf.Tensor: shape=(12,), dtype=float64, numpy=
array([729., 756., 757., 802., 721., 737., 785., 762., 771., 725., 768.,
       747.])>

In [257]:
yearly_expenses=tf.reduce_sum(expenses,axis=0)
yearly_expenses
## so this is for year. how much is it costing for 
## food, groceries, drinks and rent

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 593., 1147., 7200.,  120.])>